on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."    
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Check artifact size
        run: |
          du -sh dist/
          if [[ $(du -s dist/ | awk '{print $1}') -gt 10000000 ]]; then exit 1; fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist.tar.gz
          if-no-files-found: error
        run: |
          tar -czvf dist.tar.gz dist/
      - name: List build files in the repository    
        run: |
          ls ${{ github.workspace }}/dist   
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2