on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."    
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
        #actions/upload-artifact default name is artifact, but actions/deploy-pages default name is github-pages, so change it
          name: github-pages
          path: 'dist/'
          if-no-files-found: error
      - name: List build files in the repository    
        run: |
            ls ${{ github.workspace }}/dist   
  deploy:
    environment:
      name: github-pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/dist/